data_path: './data/cifar100'
dataset: 'cifar100'
alpha: 4
num_epochs: 350
num_class: 100
lr: 2e-2
lr_f: 2e-5
batch_size: 256
warm_up: 30
num_samples: 50000
flow_modules: 64-64-64-64
weight_decay: 5e-4
cond_size: 512
centering: True
center_momentum: 0.8
T: 0.5
flow_sp: False
d_u: 0.7
lambda_flow_u_warmup: 0.1