data_path: './data/cifar10'
dataset: 'cifar10'
alpha: 4
num_epochs: 350
num_class: 10
lr: 2e-2
lr_f: 4e-5
batch_size: 256
warm_up: 10
num_samples: 50000
flow_modules: 8-8-8-8
weight_decay: 5e-4
cond_size: 512
centering: True
center_momentum: 0.8
T: 0.5
flow_sp: False
d_u: 0.5
lambda_flow_u_warmup: 0.1